/*
 * Copyright 2024 Jeroen Gremmen
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

plugins {
  id 'java-gradle-plugin'
  alias(libs.plugins.plugin.publish)
}


layout.buildDirectory = '.build'


apply plugin: 'org.danilopianini.publish-on-central'


description = 'Repackage Gradle Plugin'
group = 'de.sayayi.plugin.gradle'
version = libs.versions.repackage.gradle.plugin.get()


java {
  withSourcesJar()
}


repositories {
  mavenCentral()
}


dependencies {
  api gradleApi()

  implementation(libs.asm.commons) {
    exclude module: 'asm-tree'
  }

  implementation(libs.ant) {
    transitive = false
  }

  implementation(libs.commons.compress) {
    exclude module: 'commons-codec'
    exclude module: 'commons-lang3'
  }

  implementation libs.plexus.utils

  testImplementation gradleTestKit()

  testImplementation libs.junit.jupiter.api
  testImplementation libs.junit.jupiter.params

  testRuntimeOnly libs.junit.jupiter.engine
  testRuntimeOnly libs.junit.platform.launcher
}


configurations {
  testAnnotationProcessor.extendsFrom annotationProcessor
  testCompileOnly.extendsFrom compileOnly
}


tasks.withType(JavaCompile).configureEach {
  javaCompiler = javaToolchains.compilerFor {
    languageVersion = JavaLanguageVersion.of(17)
  }

  options.encoding = 'UTF-8'
}


tasks.withType(Test).configureEach {
  javaLauncher = javaToolchains.launcherFor {
    languageVersion = JavaLanguageVersion.of(17)
  }

  defaultCharacterEncoding = 'UTF-8'
}


compileJava {
  sourceCompatibility = 17
  targetCompatibility = 17
}


compileTestJava {
  sourceCompatibility = 17
  targetCompatibility = 17
}


test {
  useJUnitPlatform()
}


jar.dependsOn test


gradlePlugin {
  website = 'https://github.com/jgremmen/repackage'
  vcsUrl = 'https://github.com/jgremmen/repackage'

  plugins {
    repackage { PluginDeclaration pd ->
      pd.id = 'de.sayayi.plugin.gradle.repackage'
      pd.displayName = 'Repackage Gradle Plugin'
      pd.description = 'Repackage classes and java libraries.'
      pd.implementationClass = 'de.sayayi.plugin.gradle.repackage.RepackagePlugin'
      pd.tags.set(['sayayi', 'repackage'])
    }
  }
}


def snapshot = version.toString().endsWith('-SNAPSHOT')

if (snapshot)
{
  publishing {
    repositories {
      maven {
        name = 'mavenCentralSnapshot'
        url = 'https://central.sonatype.com/repository/maven-snapshots/'

        mavenContent {
          snapshotsOnly()
        }

        credentials {
          username = rootProject.findProperty('mavenCentralPortalUsername')
          password = rootProject.findProperty('mavenCentralPortalPassword')
        }
      }
    }
  }
}


publishOnCentral {
  repoOwner = 'jgremmen'

  projectLongName = project.description
  projectDescription = 'Repackage classes and java libraries.'

  licenseName = 'Apache License, Version 2.0'
  licenseUrl = 'https://www.apache.org/licenses/LICENSE-2.0'
}


publishing {
  publications {
    withType(MavenPublication).configureEach {
      pom {
        inceptionYear = '2024'

        developers {
          developer {
            id = 'jgremmen'
            name = 'Jeroen Gremmen'
            email = 'jeroen.gremmen@sayayi.de'
          }
        }
      }
    }
  }
}


tasks.register('publishToProjectLocalRepository') {
  group = PublishingPlugin.PUBLISH_TASK_GROUP
  description = 'Create a local repository with releasable artifacts.'

  dependsOn publishOSSRHPublicationToProjectLocalRepository

  outputs.dir layout.buildDirectory.dir('project-local-repository')
}


zipMavenCentralPortalPublication.configure {
  dependsOn 'publishOSSRHPublicationToProjectLocalRepository'
}


tasks.named('zipMavenCentralPortalPublication') {
  mustRunAfter 'publishToProjectLocalRepository'
}


publishPlugins.configure {
  dependsOn 'test'
}


tasks.register('releaseArtifacts') {
  description = "Release ${version} artifacts to Maven Central Repository."
  group = 'release'

  inputs.property('version', version)
  inputs.property('snapshot', snapshot)

  dependsOn 'publishToProjectLocalRepository'

  if (snapshot)
    dependsOn 'publishOSSRHPublicationToMavenCentralSnapshotRepository'
  else
  {
    dependsOn 'zipMavenCentralPortalPublication'
    dependsOn 'validateMavenCentralPortalPublication'
    dependsOn 'releaseMavenCentralPortalPublication'
  }
}


clean {
  delete layout.projectDirectory.dir('build')
}